test:
  region: ap-southeast-1
  aws_access_key_id: replace_with_real_access_key
  aws_secret_access_key: replace_with_real_secret_key
development:
  region: ap-southeast-1
  s3_host_name: s3-ap-southeast-1.amazonaws.com
  bucket: omocha.development
  access_key_id: AKIAJH4ARYQALDXLB7YQ
  secret_access_key: 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
production:
  region: ap-southeast-1
  s3_host_name: s3.amazonaws.com
  bucket: omocha.production
  access_key_id: AKIAJH4ARYQALDXLB7YQ
  secret_access_key: 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